const NAMES = [
  'Assyrians',
  'Babylonians',
  'Choson',
  'Egyptians',
  'Greeks',
  'Hittites',
  'Minoans',
  'Persians',
  'Phoenicians',
  'Shang',
  'Sumerians',
  'Yamato',
  'Carthaginians',
  'Macedonians',
  'Palmyrans',
  'Romans',
  'Terrans',
  'Protoss',
  'Zerg',
  'United Earth Federation',
  'Cybran Nation',
  'Aeon Illuminate',
  'Allies',
  'Axis',
  'Orcs',
  'Hobbits',
  'Empire',
  'Rebels',
  'Amazons',
  'Dwarves',
  'Elves',
  'Ghouls',
  'Ratmen',
  'Skeletons',
  'Sorcerers',
  'Tritons',
  'Giants',
  'Halflings',
  'Humans',
  'Trolls',
  'Wizards',
];

Array.prototype.sample = function() {
  return this.splice(Math.random() * this.length, 1)[0];
}
